In [4]:
import warnings 
import pandas as pd
from keras.preprocessing import sequence

with warnings.catch_warnings():
    warnings.filterwarnings("ignore",category=FutureWarning)
    import numpy as np
    import random
    from dbn_tf2 import DBN
    from rbm_tf import BBRBM, GBRBM
    from util2 import normalization
    import time

# DBN Submodel -1 
For Lnc-Dis association based network features

In [5]:
path='./'

In [6]:
def pad_zero(arr):
    max_len = min((len(l) for l in arr))
    print('=====',max_len)
    
    
    new_matrix = list(map(lambda l:list(l) + [0]*(max_len - len(l)), arr))
    
    return new_matrix

In [12]:
X_train = np.load(path+'X_train.npy',allow_pickle=True)
X_test = np.load(path+'X_test.npy',allow_pickle=True)

In [13]:
X_train.shape, X_test.shape
X_train[0]

array([-0.00115849, -0.00114682, -0.00114419, ..., -0.00381877,
       -0.00304003, -0.00218662], dtype=float32)

In [41]:
a = []
a.append(np.array([1,2,3,4]))
a.append(np.array([4,5,6]))
a.append(np.array([7,8,9,0,1]))
a = np.array(a)
print(type(a))
print(type(a[0]))
#print(type(X_train))
#a = X_train.tolist()
#print(type(a))
#print(type((X_train.tolist())[0]))
b = a.tolist()
print(type(b[0]))
a_1 = sequence.pad_sequences(b,maxlen=5)
print(a_1[0])

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 1 2 3 4]


<ipython-input-41-75bdfc428ac9>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a = np.array(a)


In [43]:
max_len = 98000
#X_train_1 = np.array(sequence.pad_sequences(list(X_train),maxlen=max_len))
X_test_l = X_test.tolist()
print(X_test_l[0])
print(type(X_test_l[0]))
X_test_new = sequence.pad_sequences(X_test_l,maxlen = max_len,dtype='float32',padding='post',truncating='post')


[-0.00424254 -0.00449366 -0.00477223 ... -0.00563333 -0.00552497
 -0.00547048]
<class 'numpy.ndarray'>


In [ ]:
max_len =90000
X_train_l = X_train.tolist()
X_train_new = sequence.pad_sequences(X_train_l,maxlen = max_len,dtype='float32',padding='post',truncating='post')

In [ ]:
#X_train_1.shape, X_test_1.shape
print(X_test_new)
X_test[0]

In [52]:
#np.load(path+'train_audio_mfcc.npy')

MemoryError: Unable to allocate 15.8 GiB for an array with shape (47013, 90000) and data type float32

In [44]:
#X_train_1.shape, X_test_1.shape
print(X_test_new)
X_test[0]

[[-0.00424254 -0.00449366 -0.00477223 ...  0.00061137  0.00088815
   0.00098807]
 [-0.00013731  0.0002177   0.00046185 ...  0.          0.
   0.        ]
 [-0.00076309 -0.0008463  -0.00090619 ... -0.00224591 -0.00235472
  -0.00239231]
 ...
 [ 0.00010868  0.0001561   0.0002506  ...  0.          0.
   0.        ]
 [ 0.00027593  0.00021365  0.00016577 ...  0.          0.
   0.        ]
 [-0.0079491  -0.00784347 -0.00757084 ... -0.0011642  -0.0020968
  -0.003299  ]]


array([-0.00424254, -0.00449366, -0.00477223, ..., -0.00563333,
       -0.00552497, -0.00547048], dtype=float32)

In [5]:
#np.load(path+'train_audio_mfcc.npy')

In [3]:
hidden = 128

In [8]:
dbn1 = DBN(hidden_layers_structure=[hidden,hidden,hidden],weight_cost=0.001,batch_size=128,n_epoches=30, learning_rate_rbm=[0.0005,1e-2,1e-2],rbm_gauss_visible=True)


In [ ]:
dbn1.fit(X_train)

In [ ]:
X_train_db1 = dbn2.transform(X_train)
X_test_db1 = dbn2.transform(X_test)
X_train_db1.shape, X_test_db1.shape

In [21]:
np.save(path+'X_train_db1.npy',X_train_db1)
np.save(path+'X_test_db1.npy',X_test_db1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>


AttributeError: 'GBRBM' object has no attribute 'n_visible'

In [ ]:
X_train_db1 = dbn2.transform(X_train)
X_test_db1 = dbn2.transform(X_test)
X_train_db1.shape, X_test_db1.shape

In [ ]:
np.save(path+'X_train_db1.npy',X_train_db1)
np.save(path+'X_test_db1.npy',X_test_db1)

In [8]:
# DBN Submodel-2
for LD from Lnc-Mirna-Dis model

In [ ]:
dbn1.fit(X_train_ld)

In [10]:
np.save(path+'X_train_db1.npy',X_train_db1)
np.save(path+'X_test_db1.npy',X_test_db1)

((4314, 128), (1080, 128))

# DBN Submodel-2
for LD from Lnc-Mirna-Dis model

In [11]:
X_train_lmd = normalization(np.load(path+'X_train_lmd.npy'))
X_test_lmd = normalization(np.load(path+'X_test_lmd.npy'))

/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:190: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "
/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py

In [12]:
X_train_lmd.shape, X_test_lmd.shape

((4314, 128), (1080, 128))

In [13]:
hidden = 128

In [14]:
dbn2 = DBN(hidden_layers_structure=[hidden,hidden,hidden],weight_cost=0.001,batch_size=4,n_epoches=30, learning_rate_rbm=[0.0005,1e-2,1e-2],rbm_gauss_visible=True)


In [15]:
dbn2.fit(X_train_lmd)

In [16]:
X_train_db2 = dbn2.transform(X_train_lmd)
X_test_db2 = dbn2. transform(X_test_lmd)
X_train_db2.shape, X_test_db2.shape

((4314, 128), (1080, 128))

In [17]:
np.save(path+'X_train_db2.npy',X_train_db2)
np.save(path+'X_test_db2.npy',X_test_db2)

# Combined DBN

In [18]:
X_train_db1 = normalization(np.load(path+'X_train_db1.npy'))
X_train_db2 = normalization(np.load(path+'X_train_db2.npy'))
X_test_db1 = normalization(np.load(path+'X_test_db1.npy'))
X_test_db2 = normalization(np.load(path+'X_test_db2.npy'))

X_db_train =np.concatenate((X_train_db1,X_train_db2),axis=1)
X_db_test =np.concatenate((X_test_db1,X_test_db2),axis=1)


# X_train = np.concatenate((X_train_db1,X_train_db2),axis=1)
X_db_train.shape, X_db_test.shape

/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:190: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "
/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/home/manu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_data.py

((4314, 256), (1080, 256))

In [ ]:
#X_test = np.concatenate((X_test_db1,X_test_db2),axis=1)
#X_test.shape

In [19]:
hidden = 256
#hidden=128

In [20]:
#dbn_combined = DBN(hidden_layers_structure=[hidden,hidden,hidden],weight_cost=0.001,batch_size=4,n_epoches=30,learning_rate_rbm=[1e-2,1e-2,1e-2])
dbn_combined = DBN(hidden_layers_structure=[hidden,hidden,hidden],weight_cost=0.001,batch_size=4,n_epoches=30, learning_rate_rbm=[0.0005,1e-2,1e-2],rbm_gauss_visible=True)

In [21]:
dbn_combined.fit(X_db_train)

In [22]:
X_train_combined = dbn_combined.transform(X_db_train)
X_test_combined = dbn_combined. transform(X_db_test)

In [23]:
np.save(path+'X_train_combined.npy',X_train_combined)
np.save(path+'X_test_combined.npy',X_test_combined)